[[production.servers]]
host = "pfcace.de"
username = "ffy"
password = "V1_;U3<jC}>_Go]G~csX"
sides = ["api", "web"]
packageManagerCommand = "yarn"
monitorCommand = "pm2"
path = "/var/www/production.pfcace.de"
processNames = ["api"]
repo = "git@github.com:pcace/redwood-tutorial.git"
branch = "main"
keepReleases = 5
